### PR TITLE
Basic implementation of vue.js

### PR DESCRIPTION
**Pull request by daggerhart**
Related: #43 

Each window's html is broken down into vue components, effectively making each window into a simple vue.js app. There are likely a few components that can be merged and made re-usable in the future (such as "composer frames").

### CODE REVIEW

**Comment by daggerhart** [comment]
Updated the PR to pass some simple tests. 
Also include an updated electron package information due to issues between different computers.

**Comment by mglaman** [comment]
All for it! @daggerhart I'm willing to just merge this to kick it off. The Mac build fail looks like it's trying to build linux when it should only build Mac, so can fix that in follow up

**Comment by daggerhart** [comment]
Awesome! I'm looking forward to moving on more of the UI/X stuff once we have the foundation in place.

**Comment by mglaman** [comment]
@daggerhart is that an approval to merge this sucker? Not sure if there's anything else you wanted to quick follow up.

**Comment by daggerhart** [comment]
@mglaman yes! Sorry, didn't know you were asking me. Please merge

**Comment by mglaman** [comment]
:P Yeah I was pretty vague in that, I realize. MERGING AWAY! 💥 💣 💥

**Pull request merged**
